# fly.toml app configuration file generated for isc-inventory-back-purple-fire-9139 on 2025-05-26T19:45:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'isc-inventory-back-purple-fire-9139'
primary_region = 'bog'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
