# auth/Dockerfile

# ARG JAR_FILE=target/*.jar
# COPY ${JAR_FILE} app.jar
# EXPOSE 8081
# ENTRYPOINT ["java", "-jar", "/app.jar"]

# Utiliza una imagen base ligera y eficiente en memoria
FROM eclipse-temurin:21-jre

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Define el archivo JAR de la aplicación
ARG JAR_FILE=target/*.jar

# Copia el archivo JAR al directorio de trabajo
COPY ${JAR_FILE} app.jar

# Expone el puerto en el que la aplicación escuchará
EXPOSE 8081

# Establece opciones de memoria para la JVM
ENV JAVA_OPTS="-XX:MaxRAM=70m"

# Comando de inicio de la aplicación
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
