# Etapa 1: Construcción del proyecto
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copiar pom del proyecto padre y de los módulos
COPY ../pom.xml .
COPY ../shared/pom.xml shared/pom.xml
COPY ../api/pom.xml api/pom.xml
COPY pom.xml .
COPY . .

# Compilar solo el módulo auth y sus dependencias
RUN mvn clean package -pl auth -am -DskipTests

# Etapa 2: Imagen ligera para producción
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/auth/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]