FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app
COPY ../.. .

RUN mvn clean package -pl auth -am -DskipTests -Dgit.commit.id.skip=true

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/auth/target/auth-*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]