FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app
COPY ../.. .

RUN mvn clean package -pl api -am -DskipTests -Dgit.commit.id.skip=true

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/api/target/api-*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-Djava.awt.headless=true", "-jar", "app.jar"]